import os

from dotenv import load_dotenv

load_dotenv()

TOKEN = os.environ['BOT_TOKEN']
SUPPORT_USERNAME = os.environ['SUPPORT_USERNAME']
BOT_NAME = os.environ['BOT_NAME']

POSTGRES_HOST = os.environ['POSTGRES_HOST']
POSTGRES_PORT = int(os.environ['POSTGRES_PORT'])
POSTGRES_USER = os.environ['POSTGRES_USER']
POSTGRES_PASS = os.environ['POSTGRES_PASS']
POSTGRES_DBNAME = os.environ['POSTGRES_DBNAME']
POSTGRES_URI = f'postgresql+asyncpg://{POSTGRES_PASS}:{POSTGRES_PASS}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DBNAME}'

LOGGER_MONGO_HOST = os.environ['LOGGER_MONGO_HOST']
LOGGER_MONGO_PORT = int(os.environ['LOGGER_MONGO_PORT'])
LOGGER_MONGO_USER = os.environ.get('LOGGER_MONGO_USER') or None
LOGGER_MONGO_PASS = os.environ.get('LOGGER_MONGO_PASS') or None
LOGGER_MONGO_DB = os.environ['LOGGER_MONGO_DB']
LOGGER_MONGO_COLLECTION = os.environ['LOGGER_MONGO_COLLECTION']
